$(document).ready(function() {
  const eventsListBtn = $('.events-list')
  const selectedEvent = $('.events-list__item--selected')
  const eventsList = $('.events-list > ul')
  const eventsListItem = $('.events-list > ul li')
  const eventsListItemAnchor = $('.events-list > ul li > a')
  const bg = $('.event-reg__next').css('background-color')
  eventsListBtn.css('background', bg)
  eventsListBtn.css('box-shadow', `0 0.13rem 2rem ${bg}`)
  eventsListBtn.css('color', bg)
  eventsListItemAnchor.on('click', () => {
    eventsList.toggleClass('showlist')
  })
  eventsListItem.on('click', function() {
    const text = $(this)
      .children('a')
      .text()
    console.log($(this))
    console.log($(this).children('a'))
    selectedEvent.text(text)
  })
})
